image: Previous Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: CurrencyDotNet.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\CurrencyDotNet.Test\bin\Debug\CurrencyDotNet.Test.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"
