name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.*'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-
      - name: Sonarqube Install
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Sonarqube Analyze
        run: dotnet sonarscanner begin /k:"CurrenctDotNET" /d:sonar.host.url="http://51.91.145.77:32655"  /d:sonar.login="f00c13fd13e2ce567dcff88c7048eff4bd775ba2"
        run: dotnet build
        run: dotnet sonarscanner end /d:sonar.login="f00c13fd13e2ce567dcff88c7048eff4bd775ba2"
      - name: Test
        run: dotnet test --no-restore --verbosity normal